source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:letgoapp/letgo-ios-specs.git'

use_frameworks!

platform :ios, "9.0"

target 'LGLogin_Example' do
  pod 'LGComponents/LGLogin', :path => '../../'

  target 'LGLogin_Tests' do
    inherit! :search_paths

    pod 'Quick', '1.2.0'
    pod 'Nimble', '7.0.2'
  end
end
