platform :ios, '9.0'
 
workspace '../Restart.xcworkspace'

use_frameworks!

def firebase 
  pod 'Firebase/Auth', '~> 5.6.0'
end

target 'Restart' do
  firebase
end

target 'Data' do
  project 'Features/Foundation/Data/Data.xcodeproj'
  firebase
end

target 'SignUpTests' do
  project 'Features/Product/SignUp/SignUp.xcodeproj'
  firebase
end

target 'SearchTests' do
  project 'Features/Product/Search/Search.xcodeproj'
  firebase
end

target 'ListingTests' do
  project 'Features/Product/Listing/Listing/Listing.xcodeproj'
  firebase
end
