min_fastlane_version("2.72.0")

default_platform(:ios)

platform :ios do
  before_all do
  end

  desc "Bootstrap project"
  lane :bootstrap do 
    _carthage(false)
  end

  desc "Update carthage dependencies"
  lane :update_carthage do 
    _carthage(true)
  end

  desc "Run all tests"
  lane :test do 
    test_foundation
    test_signup  
  end

  desc "Run tests for foundation feature frameworks"
  lane :test_foundation do 
    test(
      project: "App/Features/Foundation/UI/UI.xcodeproj", 
      scheme: "UI")

    test(
      project: "App/Features/Foundation/Data/Data.xcodeproj", 
      scheme: "Data")
  end

  desc "Runs tests for Signup framework"
  lane :test_signup do
    test(
      project: "App/Features/Product/SignUp/SignUp.xcodeproj", 
      scheme: "SignUp")
  end

  def _carthage(update)
    command = update ? "update": "bootstrap"
    carthage(
      command: command,
      platform: 'iOS',
      use_binaries: false,
      configuration: 'Debug'
    )
  end

  def test(project:, scheme:)
    scan(
      project: project,
      scheme: scheme,
      code_coverage: true,
      clean: true,
      devices: ['iPhone 7']
    )
  end 


  after_all do |lane|
  end

  error do |lane, exception|
  end
end