//
//  ProductCarouselViewModel.swift
//  LetGo
//
//  Created by Isaac Roldan on 14/4/16.
//  Copyright © 2016 Ambatana. All rights reserved.
//

import LGCoreKit
import RxSwift

protocol ProductCarouselViewModelDelegate: BaseViewModelDelegate {
    func vmRefreshCurrent()
    func vmRemoveMoreInfoTooltip()
    func vmShowOnboarding()
}

enum CarouselMovement {
    case tap, swipeLeft, swipeRight, initial
}

class ProductCarouselViewModel: BaseViewModel {

    // Paginable
    let firstPage: Int = 0
    var nextPage: Int = 1
    var isLastPage: Bool
    var isLoading: Bool = false

    var currentProductViewModel: ProductViewModel?
    var startIndex: Int = 0
    weak var delegate: ProductCarouselViewModelDelegate?
    weak var navigator: ProductDetailNavigator? {
        didSet {
            currentProductViewModel?.navigator = navigator
        }
    }

    var objectChanges: Observable<CollectionChange<ProductCarouselCellModel>> {
        return objects.changesObservable
    }

    var objectCount: Int {
        return objects.value.count
    }

    var shouldShowMoreInfoTooltip: Bool {
        return !keyValueStorage[.productMoreInfoTooltipDismissed]
    }

    let showKeyboardOnFirstAppearance: Bool

    let productInfo = Variable<ProductVMProductInfo?>(nil)
    let productImageURLs = Variable<[URL]>([])
    let userInfo = Variable<ProductVMUserInfo?>(nil)

    let navBarButtons = Variable<[UIAction]>([])
    let actionButtons = Variable<[UIAction]>([])

    let status = Variable<ProductViewModelStatus>(.pending)
    let isFeatured = Variable<Bool>(false)

    let quickAnswers = Variable<[QuickAnswer]>([])
    let quickAnswersAvailable = Variable<Bool>(false)
    let quickAnswersCollapsed: Variable<Bool>

    let directChatEnabled = Variable<Bool>(false)
    var directChatPlaceholder = Variable<String>("")
    let directChatMessages = CollectionVariable<ChatViewMessage>([])

    let editButtonState = Variable<ButtonState>(.hidden)
    let isFavorite = Variable<Bool>(false)
    let favoriteButtonState = Variable<ButtonState>(.enabled)
    let shareButtonState = Variable<ButtonState>(.hidden)
    let bumpUpBannerInfo = Variable<BumpUpInfo?>(nil)


    /* Static required data on viewController:

     - owner: avatar, avatarPlaceholder, name, userId
     - directChatMessages
     - product
     - productInfo: title, price, productTitleAutogenerated, productTitleAutoTranslated, productAddress, productDistance, productDescription, productLocation
     - productImagesCount
     - navbarbuttons
     - actionButtons
     - editButtonState
     - shareButtonState
     - favoriteButtonState
     - isFavorite
     - directChatEnabled
     - quickAnswers
     - shouldShowOnboarding
     - productStatus (label, color, backgroundcolor)
     - bumpUpBannerInfo (on nil -> closeBumpUpBanner)
     
     // for more info
     - statsViewVisible
     - viewsCount, favoritesCount, productCreationDate
     - socialMessage
     - socialSharer


    */

    // Image prefetching
    fileprivate let previousImagesToPrefetch = 1
    fileprivate let nextImagesToPrefetch = 3
    fileprivate var prefetchingIndexes: [Int] = []

    fileprivate var shouldShowOnboarding: Bool {
        return !keyValueStorage[.didShowProductDetailOnboarding]
    }

    fileprivate var trackingIndex: Int?
    fileprivate var initialThumbnail: UIImage?

    private var activeDisposeBag = DisposeBag()

    fileprivate let source: EventParameterProductVisitSource
    fileprivate let productListRequester: ProductListRequester
    fileprivate var productsViewModels: [String: ProductViewModel] = [:]
    fileprivate let keyValueStorage: KeyValueStorage
    fileprivate let imageDownloader: ImageDownloaderType
    fileprivate let objects = CollectionVariable<ProductCarouselCellModel>([])

    fileprivate let disposeBag = DisposeBag()

    override var active: Bool {
        didSet {
            currentProductViewModel?.active = active
        }
    }

    // MARK: - Init

    convenience init(product: LocalProduct,
                     productListRequester: ProductListRequester,
                     source: EventParameterProductVisitSource,
                     showKeyboardOnFirstAppearIfNeeded: Bool,
                     trackingIndex: Int?) {
        self.init(productListModels: nil,
                  initialProduct: product,
                  thumbnailImage: nil,
                  productListRequester: productListRequester,
                  source: source,
                  showKeyboardOnFirstAppearIfNeeded: showKeyboardOnFirstAppearIfNeeded,
                  trackingIndex: trackingIndex)
        syncFirstProduct()
    }

    convenience init(product: Product,
                     thumbnailImage: UIImage?,
                     productListRequester: ProductListRequester,
                     source: EventParameterProductVisitSource,
                     showKeyboardOnFirstAppearIfNeeded: Bool,
                     trackingIndex: Int?) {
        self.init(productListModels: nil,
                  initialProduct: product,
                  thumbnailImage: thumbnailImage,
                  productListRequester: productListRequester,
                  source: source,
                  showKeyboardOnFirstAppearIfNeeded: showKeyboardOnFirstAppearIfNeeded,
                  trackingIndex: trackingIndex)
    }

    convenience init(productListModels: [ProductCellModel]?,
         initialProduct: Product?,
         thumbnailImage: UIImage?,
         productListRequester: ProductListRequester,
         source: EventParameterProductVisitSource,
         showKeyboardOnFirstAppearIfNeeded: Bool,
         trackingIndex: Int?) {
        self.init(productListModels: productListModels,
                  initialProduct: initialProduct,
                  thumbnailImage: thumbnailImage,
                  productListRequester: productListRequester,
                  source: source,
                  featureFlags: FeatureFlags.sharedInstance,
                  keyValueStorage: KeyValueStorage.sharedInstance,
                  imageDownloader: ImageDownloader.sharedInstance,
                  showKeyboardOnFirstAppearIfNeeded: showKeyboardOnFirstAppearIfNeeded,
                  trackingIndex: trackingIndex)
    }

    init(productListModels: [ProductCellModel]?,
         initialProduct: Product?,
         thumbnailImage: UIImage?,
         productListRequester: ProductListRequester,
         source: EventParameterProductVisitSource,
         featureFlags: FeatureFlaggeable,
         keyValueStorage: KeyValueStorage,
         imageDownloader: ImageDownloaderType,
         showKeyboardOnFirstAppearIfNeeded: Bool,
         trackingIndex: Int?) {
        if let productListModels = productListModels {
            self.objects.appendContentsOf(productListModels.flatMap(ProductCarouselCellModel.adapter))
        } else {
            self.objects.appendContentsOf([initialProduct].flatMap{$0}.map(ProductCarouselCellModel.init))
        }
        self.initialThumbnail = thumbnailImage
        self.productListRequester = productListRequester
        self.source = source
        self.isLastPage = productListRequester.isLastPage(productListModels?.count ?? 0)
        self.keyValueStorage = keyValueStorage
        self.imageDownloader = imageDownloader
        self.showKeyboardOnFirstAppearance = source == .notifications && showKeyboardOnFirstAppearIfNeeded && featureFlags.passiveBuyersShowKeyboard
        self.quickAnswersCollapsed = Variable<Bool>(keyValueStorage[.productDetailQuickAnswersHidden])
        super.init()
        self.startIndex = indexForProduct(initialProduct) ?? 0
        self.currentProductViewModel = viewModelAtIndex(startIndex)
        self.trackingIndex = trackingIndex
        setCurrentIndex(startIndex)
        setupRxBindings()
    }
    
    
    private func syncFirstProduct() {
        currentProductViewModel?.syncProduct() { [weak self] in
            guard let strongSelf = self else { return }
            guard let product = strongSelf.currentProductViewModel?.product.value else { return }
            let newModel = ProductCarouselCellModel(product: product)
            strongSelf.objects.removeAtIndex(strongSelf.startIndex)
            strongSelf.objects.insert(newModel, atIndex: strongSelf.startIndex)
            strongSelf.delegate?.vmRefreshCurrent()
        }
    }
    
    
    func indexForProduct(_ product: Product?) -> Int? {
        guard let product = product else { return nil }
        for i in 0..<objects.value.count {
            switch objects.value[i] {
            case .productCell(let data):
                if data.objectId == product.objectId {
                    return i
                }
            }
        }
        return nil
    }


    // MARK: - Public Methods

    func close() {
        navigator?.closeProductDetail()
    }

    func moveToProductAtIndex(_ index: Int, delegate: ProductViewModelDelegate, movement: CarouselMovement) {
        guard let viewModel = viewModelAtIndex(index) else { return }
        currentProductViewModel?.active = false
        currentProductViewModel = viewModel
        currentProductViewModel?.delegate = delegate
        currentProductViewModel?.active = true
        let feedPosition = movement.feedPosition(for: trackingIndex)
        currentProductViewModel?.trackVisit(movement.visitUserAction, source: source, feedPosition: feedPosition)

        setupCurrentProductVMRxBindings(forIndex: index)

        prefetchNeighborsImages(index, movement: movement)

        if shouldShowOnboarding {
            self.delegate?.vmShowOnboarding()
        }
    }

    func productAtIndex(_ index: Int) -> Product? {
        guard 0..<objectCount ~= index else { return nil }
        let item = objects.value[index]
        switch item {
        case .productCell(let product):
            return product
        }
    }
    
    func thumbnailAtIndex(_ index: Int) -> UIImage? {
        if index == startIndex { return initialThumbnail }
        guard 0..<objectCount ~= index else { return nil }
        return viewModelAtIndex(index)?.thumbnailImage
    }
    
    func viewModelAtIndex(_ index: Int) -> ProductViewModel? {
        guard let product = productAtIndex(index) else { return nil }
        return getOrCreateViewModel(product)
    }

    func viewModelForProduct(_ product: Product) -> ProductViewModel {
        return ProductViewModel(product: product, thumbnailImage: nil, navigator: navigator)
    }

    func userAvatarPressed() {
        currentProductViewModel?.openProductOwnerProfile()
    }

    func directMessagesItemPressed() {
        currentProductViewModel?.chatWithSeller()
    }
    
    func didOpenMoreInfo() {
        currentProductViewModel?.trackVisitMoreInfo()
        keyValueStorage[.productMoreInfoTooltipDismissed] = true
        delegate?.vmRemoveMoreInfoTooltip()
    }

    func showOnboardingButtonPressed() {
        delegate?.vmShowOnboarding()
    }

    func quickAnswersShowButtonPressed() {
        quickAnswersCollapsed.value = false
    }

    func quickAnswersCloseButtonPressed() {
        quickAnswersCollapsed.value = true
    }

    func send(quickAnswer: QuickAnswer) {
        currentProductViewModel?.sendQuickAnswer(quickAnswer: quickAnswer)
    }

    func send(directMessage: String, isDefaultText: Bool) {
        currentProductViewModel?.sendDirectMessage(directMessage, isDefaultText: isDefaultText)
    }

    func editButtonPressed() {
        currentProductViewModel?.editProduct()
    }

    func favoriteButtonPressed() {
        currentProductViewModel?.switchFavorite()
    }

    func shareButtonPressed() {
        currentProductViewModel?.shareProduct()
    }
    
    // MARK: - Private Methods
    
    private func getOrCreateViewModel(_ product: Product) -> ProductViewModel? {
        guard let productId = product.objectId else { return nil }
        if let vm = productsViewModels[productId] {
            return vm
        }
        let vm = viewModelForProduct(product)
        productsViewModels[productId] = vm
        return vm
    }

    private func setupRxBindings() {
        quickAnswersCollapsed.asObservable().skip(1).bindNext { [weak self] collapsed in
            self?.keyValueStorage[.productDetailQuickAnswersHidden] = collapsed
        }.addDisposableTo(disposeBag)
    }

    private func setupCurrentProductVMRxBindings(forIndex index: Int) {
        activeDisposeBag = DisposeBag()
        guard let currentVM = currentProductViewModel else { return }
        currentVM.product.asObservable().skip(1).bindNext { [weak self] updatedProduct in
            guard let strongSelf = self else { return }
            guard 0..<strongSelf.objectCount ~= index else { return }
            strongSelf.objects.replace(index..<(index+1), with: [ProductCarouselCellModel(product: updatedProduct)])
            strongSelf.delegate?.vmRefreshCurrent()
        }.addDisposableTo(activeDisposeBag)

        currentVM.status.asObservable().bindTo(status).addDisposableTo(activeDisposeBag)
        isFeatured.value = currentVM.isShowingFeaturedStripe

        currentVM.productInfo.asObservable().bindTo(productInfo).addDisposableTo(activeDisposeBag)
        currentVM.productImageURLs.asObservable().bindTo(productImageURLs).addDisposableTo(activeDisposeBag)
        currentVM.userInfo.asObservable().bindTo(userInfo).addDisposableTo(activeDisposeBag)

        currentVM.actionButtons.asObservable().bindTo(actionButtons).addDisposableTo(activeDisposeBag)
        currentVM.navBarButtons.asObservable().bindTo(navBarButtons).addDisposableTo(activeDisposeBag)

        quickAnswers.value = currentVM.quickAnswers
        currentVM.directChatEnabled.asObservable().bindTo(quickAnswersAvailable).addDisposableTo(activeDisposeBag)

        currentVM.directChatEnabled.asObservable().bindTo(directChatEnabled).addDisposableTo(activeDisposeBag)
        currentVM.directChatMessages.bindTo(directChatMessages).addDisposableTo(activeDisposeBag)
        directChatPlaceholder.value = currentVM.directChatPlaceholder

        currentVM.editButtonState.asObservable().bindTo(editButtonState).addDisposableTo(activeDisposeBag)
        currentVM.isFavorite.asObservable().bindTo(isFavorite).addDisposableTo(activeDisposeBag)
        currentVM.favoriteButtonState.asObservable().bindTo(favoriteButtonState).addDisposableTo(activeDisposeBag)
        currentVM.shareButtonState.asObservable().bindTo(shareButtonState).addDisposableTo(activeDisposeBag)
        currentVM.bumpUpBannerInfo.asObservable().bindTo(bumpUpBannerInfo).addDisposableTo(activeDisposeBag)
    }
}

extension ProductCarouselViewModel: Paginable {
    func retrievePage(_ page: Int) {
        let isFirstPage = (page == firstPage)
        isLoading = true
        
        let completion: ProductsCompletion = { [weak self] result in
            guard let strongSelf = self else { return }
            self?.isLoading = false
            if let newProducts = result.value {
                strongSelf.nextPage = strongSelf.nextPage + 1
                strongSelf.objects.appendContentsOf(newProducts.map(ProductCarouselCellModel.init))
                
                strongSelf.isLastPage = strongSelf.productListRequester.isLastPage(newProducts.count)
                if newProducts.isEmpty && !strongSelf.isLastPage {
                    strongSelf.retrieveNextPage()
                }
            }
        }
        
        if isFirstPage {
            productListRequester.retrieveFirstPage(completion)
        } else {
            productListRequester.retrieveNextPage(completion)
        }
    }
}


// MARK: > Image PreCaching

extension ProductCarouselViewModel {
    func prefetchNeighborsImages(_ index: Int, movement: CarouselMovement) {
        let range: CountableClosedRange<Int>
        switch movement {
        case .initial:
            range = (index-previousImagesToPrefetch)...(index+nextImagesToPrefetch)
        case .tap, .swipeRight:
            range = (index+1)...(index+nextImagesToPrefetch)
        case .swipeLeft:
            range = (index-previousImagesToPrefetch)...(index-1)
        }
        var imagesToPrefetch: [URL] = []
        for index in range {
            guard !prefetchingIndexes.contains(index) else { continue }
            prefetchingIndexes.append(index)
            if let prevProduct = productAtIndex(index), let imageUrl = prevProduct.images.first?.fileURL {
                imagesToPrefetch.append(imageUrl)
            }
        }
        imageDownloader.downloadImagesWithURLs(imagesToPrefetch)
    }
}


// MARK: - Tracking

extension CarouselMovement {
    var visitUserAction: ProductVisitUserAction {
        switch self {
        case .tap:
            return .tap
        case .swipeLeft:
            return .swipeLeft
        case .swipeRight:
            return .swipeRight
        case .initial:
            return .none
        }
    }
    func feedPosition(for index: Int?) -> EventParameterFeedPosition {
        guard let index = index else  { return .none }
        switch self {
        case .tap, .swipeLeft, .swipeRight:
            return .none
        case .initial:
            return .position(index: index)
        }
    }
}
