//
//  Product+Title.swift
//  LetGo
//
//  Created by Albert Hernández López on 15/04/16.
//  Copyright © 2016 Ambatana. All rights reserved.
//

import LGCoreKit

extension Product {

    var title: String? {
        if let name = name?.trim, !name.isEmpty {
            return name.capitalizedFirstLetterOnly
        } else if let nameAuto = nameAuto?.trim, !nameAuto.isEmpty {
            return nameAuto.capitalizedFirstLetterOnly
        }
        return nil
    }

    var description: String? {
        guard let descr = descr else { return nil }
        return descr.capitalizedFirstLetterOnly
    }

    var isTitleAutoGenerated: Bool {
        if let name = name?.trim, !name.isEmpty {
            return false
        } else if let nameAuto = nameAuto?.trim, !nameAuto.isEmpty {
            return true
        }
        return false
    }
    func isTitleAutoTranslated(_ countryHelper: CountryHelper) -> Bool {
        guard isTitleAutoGenerated else { return false }
        guard let languageCode = countryHelper.countryLanguageForProduct(self) else { return false }
        return languageCode != "en"
    }
}
